project:
  type: book

book:
  title: "Akustična fonetika -- vaje"
  author: "Luka Horjak"
  date: "7 June 2026"
  chapters:
    - index.qmd
    - poglavja\kratka-navodila-za-praat.qmd
    - poglavja\samoglasniki.qmd
    - poglavja\osnovna-frekvenca.qmd
    - poglavja\tonemski-naglas.qmd
    - poglavja\soglasniki.qmd
    - poglavja\hitrost-govora.qmd
    - references.qmd
   
bibliography: references.bib
csl: apa.csl

lang: sl


format:
  html:
    theme:
      - cosmo
      - brand

toc-depth: 6

